import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the GitHub repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // ws (used for live/streaming voice transcription, see
    // src/realtimeTranscribe.ts) guards its optional native accelerators
    // with try/catch require() - these two must stay unbundled or esbuild
    // fails trying to resolve native addons that aren't actually installed.
    // ws falls back to its pure-JS implementation automatically when
    // they're absent; a standard pattern for bundling ws with esbuild.
    "bufferutil",
    "utf-8-validate",
    ...builtinModules,
  ],
  format: "cjs",
  // Without this, esbuild leaves dynamic import("child_process") etc. as
  // literal browser-style imports instead of lowering them to require() -
  // Electron's renderer can't resolve those, so every Node-dependent
  // feature (CLI mode, whisper, meeting capture) fails at runtime with
  // "Failed to resolve module specifier".
  platform: "node",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
